---
title: "reading_data_from_web"
author: "Dantong Zhu"
date: "2021/10/19"
output: html_document
---
```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##Scrape a table

read in the html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = 
  read_html(url)

drug_use_df = 
  drug_use_html %>% 
  html_table() %>% 
  first() %>%
  slice(-1)
```

#star wars

```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(sw_url)

title_vec = 
  swm_html %>% 
  html_elements(".lister-item-header a") %>%
  html_text()

sw_revenue = 
  swm_html %>% 
  html_element(".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    gross_rev = sw_revenue
  )
```

# get some water data
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```

#brfss
```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content()
  
```

# pokemon api
```{r}
poke_data = 
  GET("https://pokeapi.co/api/v2/pokemon/1") %>% 
  content()

poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```



